### ISSUE TITLE
respec-mermaid with markdown possible?

### ISSUE THREAD

**Issue by bequrios** [w3c/respec-mermaid#9]
We try to use respec-mermaid with a respec installation that uses the possibility of writing content in markdown. How can we insert mermaid code into markdown sections? If one just uses

```html
<figure>
  <pre class="diagram mermaid">
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
    Alice-)John: See you later!
  </pre>
  <figcaption>A sequence diagram example</figcaption>
</figure>
```

as in the instructions, this code gets wrapped into `<code class="hljs">` and will be shown as "code" and not as mermaid diagram in the output. Is there a possibility to use the fantastic respec-mermaid with markdown?

**Comment by sanderke** [comment]
It works if you add this line to your ReSpec configuration:
```js
postProcess: [window.respecMermaid.createFigures]
```
as opposed to `preProcess` mentioned in the README.

You could even use backticks so it renders on GitHub as well:

````html
<figure>

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
<figcaption>Mermaid example</figcaption>
</figure>
````
(the empty line is necessary)

**Comment by bequrios** [comment]
@sanderke Thanks a lot for the solution that works like a charm!
